### ISSUE TITLE
genius idea

### ISSUE THREAD

**Issue by akioweh** [NazierH/Education-Perfect-Answer-Interceptor#1]
not an issue but idfk how to contact ppl on github

check out [my thing here](https://github.com/KEN-2000l/EducationPerfected)
it auto-answers EP word-based translation questions fully automatically...
I first scrape the list starter page with the word lists to learn the pairs
then during the task I read the question to find the answer

by scraping the visible page elements, however, I can't make it work with audio tasks (dictation or listening)
but after looking at your findings here, I could mess with the https requests I think?
I'm pretty lazy so if you see good opportunities go ahead and make some well-rounded script that does all types of tasks :D

**Comment by NazierH** [comment]
This is a great idea! I think if we listen for the HTTPS request, it should give us the answers,.I think your project in v1 had a list of words in an array, Im not sure if thats the same in v2 but it could get the words fron the request and add that to the list.

**Comment by akioweh** [comment]
I fiddled around with stuff a bit
I do store the words in an array but that's not really important

the problem is... can you figure out the answer for each question during a task? I see how the response contains question-answer pairs... but not sure about how they are shuffled to appear in the task?
because for audio mode there is no way to tell what the question is from the local html

**Comment by garv-shah** [comment]
i think the local html would still have a question id embedded in it, so we could possibly use that to identify them?

**Comment by akioweh** [comment]
I looked thru the html and didn't find anything

everything is in scripts and as usual there's about 5 million lines

**Comment by Annoying-Doge** [comment]
I know for a fact duolingo Has the question embedded in it, but I am not so sure about EP
